apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.fullname }}-es
  namespace: {{ .Release.Namespace }}
spec:
  version: "{{ .Values.elasticsearch.version }}"
  nodeSets:
    - name: default
      count: {{ .Values.elasticsearch.count }}
      config:
        node.roles: {{ toJson .Values.elasticsearch.roles }}
        node.store.allow_mmap: false
      podTemplate:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: {{ .Values.fullname }}-es
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
                  memory: {{ .Values.elasticsearch.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
                  memory: {{ .Values.elasticsearch.resources.limits.memory }}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: {{ .Values.elasticsearch.persistence.storageClassName }}
            resources:
              requests:
                storage: {{ .Values.elasticsearch.persistence.size }}

  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.elasticsearch.http.tls.selfSignedCertificate.disabled }}
