apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.clusterName }}
spec:
  version: {{ .Values.elasticsearch.version }}
  nodeSets:
    - name: masterdata
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.roles: ["master", "data", "ingest"]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          # initContainers:
          # - name: sysctl
          #   securityContext:
          #     privileged: true
          #     runAsUser: 0
          #   command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                {{- toYaml .Values.elasticsearch.resources | nindent 16 }}
              env:
              - name: ES_JAVA_OPTS
                value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.elasticsearch.storage }}