apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./elk-cluster/elasticsearch-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./elk-cluster/elasticsearch-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system