apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elasticsearch-operator
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster/my-gke-cluster/elasticsearch-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system