apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.fullname }}-kibana
  namespace: {{ .Release.Namespace }}
spec:
  version: "{{ .Values.kibana.version }}"
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef }}-es
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: {{ .Values.kibana.resources.requests.cpu }}
              memory: {{ .Values.kibana.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kibana.resources.limits.cpu }}
              memory: {{ .Values.kibana.resources.limits.memory }}

  http:
    service:
      spec:
        type: {{ .Values.kibana.service.type }}
        ports:
          - port: {{ .Values.kibana.service.port }}
            name: http