---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    eck.k8s.elastic.co/license: basic
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "A Kibana version is required" .Values.version }}
  {{- /* 
    The following templates with 'or' are to allow both .spec.field and .field to be set for backwards 
    compatibility purposes. See https://github.com/elastic/cloud-on-k8s/pull/8192 for details.
  */ -}}
  {{- with or ((.Values.spec).image) (.Values.image) }}
  image: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).count) (.Values.count) }}
  count: {{ . }}
  {{- end }}
  {{- $esRef := or ((.Values.spec).elasticsearchRef) (.Values.elasticsearchRef) }}
  {{- if not ($esRef).name }}
  {{ fail "An elasticsearchRef is required" }}
  {{- end }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef.name }}
  config:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).http) (.Values.http) }}
  http:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).podTemplate) (.Values.podTemplate) }}
  podTemplate:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).revisionHistoryLimit) (.Values.revisionHistoryLimit) }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).secureSettings) (.Values.secureSettings) }}
  secureSettings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with or ((.Values.spec).serviceAccountName) (.Values.serviceAccountName) }}
  serviceAccountName: {{ . }}
  {{- end }}
  {{- with or ((.Values.spec).monitoring) (.Values.monitoring) }}
  monitoring:
    {{- toYaml . | nindent 4 }}
  {{- end }}

# ---
# {{- if .Values.ingress.enabled -}}
# {{- $pathType := .Values.ingress.pathType | default "Prefix" -}}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "kibana.fullname" . }}
#   labels:
#     {{- include "kibana.labels" . | nindent 4 }}
#     {{- with .Values.ingress.labels }}
#     {{- toYaml . | nindent 4 }}
#     {{- end }}
#   {{- if .Values.ingress.annotations }}
#   annotations:
#     {{- with .Values.ingress.annotations }}
#     {{- toYaml . | nindent 4 }}
#     {{- end }}
#   {{- end }}
# spec:
#   {{- if .Values.ingress.className }}
#   ingressClassName: {{ .Values.ingress.className | quote }}
#   {{- end }}
#   {{- if .Values.ingress.tls.enabled }}
#   tls:
#   - hosts:
#   {{- range .Values.ingress.hosts }}
#     - {{ .host | quote }}
#   {{- end }}
#   {{- if .Values.ingress.tls.secretName }}
#     secretName: {{ .Values.ingress.tls.secretName }}
#   {{- else }}
#     secretName: {{ include "kibana.fullname" . }}-kb-http-certs-internal
#   {{- end }}
#   {{- end }}
#   rules:
#   {{- range .Values.ingress.hosts }}
#   {{- $hostPath := .path | default "/" }}
#   - host: {{ .host | quote }}
#     http:
#       paths:
#       - path: {{ $hostPath }}
#         pathType: {{ $pathType }}
#         backend:
#           service:
#             name: {{ include "kibana.fullname" $ }}-kb-http
#             port:
#               number: 5601
#   {{- end }}
# {{ end }}