apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch-operator
  namespace: flux-system
spec:
  interval: 1m
  path: ./elk-cluster/elasticsearch-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system