# helmrelease-elasticsearch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk-cluster
  namespace: elk-cluster
spec:
  interval: 1m
  releaseName: elk-iot-cluster
  targetNamespace: elk-cluster
  chart:
    spec:
      chart: ./charts/elasticsearch
      sourceRef:
        kind: GitRepository
        name: eck-elasticsearch-stack
        namespace: flux-system
  values:
    # Identity
    fullnameOverride: "elk-iot-cluster"
    version: 8.8.0

    # Topology: 3 master+data nodes
    nodeSets:
      - name: default
        count: 3
        config:
          node.store.allow_mmap: false
          node.roles:
            - master
            - data
        podTemplate:
          spec:
            containers:
              - name: elasticsearch
                resources:
                  requests:
                    cpu: 500m
                    memory: 1Gi
                  limits:
                    cpu: 1
                    memory: 1Gi
    http:
      service:
        spec:
          type: LoadBalancer
          ports:
            - name: http
              port: 9200
              targetPort: 9200
          externalTrafficPolicy: Local
          
    # Rolling upgrades
    updateStrategy:
      changeBudget:
        maxSurge: 1
        maxUnavailable: 0

    # PodDisruptionBudget
    podDisruptionBudget:
      disabled: false
      spec:
        minAvailable: 2
        selector:
          matchLabels:
            elasticsearch.k8s.elastic.co/cluster-name: elk-iot-cluster

    # Clean up PVCs on delete
    volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion

    # Do not expose ES HTTP directly
    ingress:
      enabled: false

---
# helmrelease-kibana.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk-cluster
spec:
  interval: 5m
  releaseName: kibana-iot
  targetNamespace: elk-cluster
  chart:
    spec:
      chart: ./charts/kibana
      sourceRef:
        kind: GitRepository
        name: eck-elasticsearch-stack
        namespace: flux-system
      version: 8.8.0
  values:
    # Basic settings
    fullnameOverride: "kibana-iot"
    version: 8.8.0
    count: 1

    # Point to the ES service in-cluster
    elasticsearchRef:
      name: elk-iot-cluster
    config:
      server:
        publicBaseUrl: "http://elk.iot.cluster.local:5601"
    http:
      tls:
        selfSignedCertificate:
          disabled: true
    ingress:
      enabled: false
