# helmrelease-elasticsearch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elk-cluster
  namespace: elk-cluster
spec:
  interval: 1m
  releaseName: elk-iot-cluster
  targetNamespace: elk-cluster
  chart:
    spec:
      chart: ./charts/elasticsearch
      sourceRef:
        kind: GitRepository
        name: eck-elasticsearch-stack
        namespace: flux-system
  values:
    # Identity
    fullname: "elk-iot-cluster"
    elasticsearch:
      version: "8.10.0"
      count: 3
      roles: ["master", "data"]
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      persistence:
        size: 5Gi
        storageClassName: standard
      # disable TLS on HTTP for simplicity (in-cluster only)
      http:
        tls:
          selfSignedCertificate:
            disabled: true
              
        # Rolling upgrades
        updateStrategy:
          changeBudget:
            maxSurge: 1
            maxUnavailable: 0

        # PodDisruptionBudget
        podDisruptionBudget:
          disabled: false
          spec:
            minAvailable: 2
            selector:
              matchLabels:
                elasticsearch.k8s.elastic.co/cluster-name: elk-iot-cluster

        # Clean up PVCs on delete
        volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion

        # Do not expose ES HTTP directly
        ingress:
          enabled: false

---
# helmrelease-kibana.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: elk-cluster
spec:
  interval: 5m
  releaseName: kibana-iot
  targetNamespace: elk-cluster
  chart:
    spec:
      chart: ./charts/kibana
      sourceRef:
        kind: GitRepository
        name: eck-elasticsearch-stack
        namespace: flux-system
      version: 8.8.0
  values:
    # Basic settings
    kibana:
      version: "8.10.0"
      count: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      service:
        type: LoadBalancer
        port: 5601
    fullname: "kibana-iot"

    # Point to the ES service in-cluster
    elasticsearchRef:
      name: elk-iot-cluster
