---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: elastic-stack
  namespace: elk-cluster
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 5601  # Port your service listens on
    type: HTTP
    requestPath: /  # Adjust the path if necessary

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: elastic-stack
  namespace: elk-cluster
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: elastic-stack
  namespace: elk-cluster
spec:
  domains:
    - elk.iot.cluster.local

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: elk-cluster
  annotations:
    # networking.gke.io/managed-certificates: elastic-stack
    # networking.gke.io/v1beta1.FrontendConfig: elastic-stack
    kubernetes.io/ingress.global-static-ip-name: elastic-stack
    kubernetes.io/ingress.class: gce
spec:
  defaultBackend:
    service:
      name: kibana-iot-kb-http
      port:
        number: 5601